services:
  - type: web
    name: youtube-downloader-api
    env: docker
    dockerfilePath: ./Dockerfile
    plan: starter
    region: oregon
    branch: main
    healthCheckPath: /health
    envVars:
      - key: PORT
        value: 5000
      - key: FLASK_ENV
        value: production
      - key: PYTHONPATH
        value: /app
    autoDeploy: true
